project_id = "hrindypsfxbiijxgtdmi"

[functions.notify-booking]
verify_jwt = true

[functions.notify-admin]
verify_jwt = true

[functions.chat-support]
verify_jwt = false

[functions.send-booking-verification]
verify_jwt = true

[functions.verify-booking]
verify_jwt = false